### PR TITLE
OAuth2 / Custom Connections Support

### PR DESCRIPTION
**Pull request by rjocoleman**
This really saved me a lot of time - thanks so much for releasing it! 

I added _very_ basic support for OAuth2 and Xero's ~new [Custom Connections](https://developer.xero.com/documentation/guides/oauth2/custom-connections) - auth methods compared [here](https://developer.xero.com/documentation/guides/oauth2/overview)

In essence, because custom connections the auth flow is handled by Xero, we just need to get an auth token.
I've used the `oauth2` gem to do this, and added some docs for the same.

The only actual, non-docs, change for this is the validation check for `access_token` (vs `token` for oauth1) as the Faraday Middleware was already working nicely 😀  

```ruby
require 'oauth2'
require 'xero/api'

client = OAuth2::Client.new(ENV['XERO_OAUTH2_CLIENT_ID'), ENV['XERO_OAUTH2_CLIENT_SECRET'], token_url: 'https://identity.xero.com/connect/token' )
client_credentials = client.client_credentials.get_token

api = Xero::Api.new(access_token: client_credentials.token)
```

As Xero has moved a little there are a number of other changes that should happen:

* Tests updated to use OAuth2 
* Remove Oauth1 (I think it's completely gone from Xero: https://devblog.xero.com/oauth-1-0a-will-soon-be-deprecated-heres-what-you-need-to-do-29e2770ea0c1)
* Support for the other OAuth2 authentication methods, but they could happen out of band like this and it just be a docs update. OR, support for doing the Oauth2 dance in this library directly.
* Token refresh support
* Update the examples

However, I'm not going to be able to do any of the above sorry - as such I don't expect this to be merged. I just wanted to leave a trail for others who might need OAuth2 and want to use this gem (it's really great and worth it - close to the metal but not _too_ close) 

Ref #6

### CODE REVIEW

**Comment by minimul** [comment]
Hey @rjocoleman – I'll take a look very soon.

**Comment by minimul** [comment]
Nice contribution @rjocoleman! 

I built in OAuth2 support to a pretty good degree so all I had to do to get the specs to pass was to add an `export XERO_API_OAUTH2_ACCESS_TOKEN=` to the local `.env` file. See `spec/support/credentials.rb` if interested.

I may make a couple more changes and then I'll release a `2.0.0` version. It'll be great if you could run off the new released version and ideally could continue to add some tips, tweaks, or just some helpful issues. 

FWIW: I'm not using the gem in production but since I do accounting integrations I'd selfishly like a better Ruby Xero library option than the current crop if I do get tapped to do a Xero integration.

Thanks again.

**Comment by minimul** [comment]
Version `2.0.0` released.

**Comment by rjocoleman** [comment]
Thanks @minimul I switched from my fork to the released version and it worked great. 
I think this closes #6 unless you want to keep it open?

**Comment by minimul** [comment]
Great!

re: #6 – You had some other todo items in there that I wanted to break into new issues. After I do that I'll close.

**Pull request merged**
